// Generated by shellyctl -- DO NOT EDIT.
// Link: Kitchen switch to hall light (id kitchen-1)
// Manual edits will be overwritten the next time this link is deployed.

let CONFIG = {
  linkId: "kitchen-1",
  srcComponent: "input:0",
  srcEvent: "single_push",
  targetIp: "192.168.1.42",
  method: "Switch.Toggle",
  params: {"id":0},
  strategy: "fallback",
  bleEnabled: true,
  bleMac: "AA:BB:CC:DD:EE:FF",
  baseTimeoutMs: 400,
  maxTimeoutMs: 1500,
  latencyFactor: 4,
  httpTimeoutSec: 3
};

let ewmaMs = 0;  // EWMA of successful LAN round-trips (ms); 0 = no samples yet
let attempt = 0; // per-attempt token: late callbacks from older attempts are ignored

function recordRtt(rtt) {
  if (ewmaMs <= 0) {
    ewmaMs = rtt;
  } else {
    ewmaMs = 0.3 * rtt + 0.7 * ewmaMs;
  }
}

function adaptiveTimeoutMs() {
  if (ewmaMs <= 0) return CONFIG.baseTimeoutMs;
  let t = ewmaMs * CONFIG.latencyFactor;
  if (t < CONFIG.baseTimeoutMs) t = CONFIG.baseTimeoutMs;
  if (t > CONFIG.maxTimeoutMs) t = CONFIG.maxTimeoutMs;
  return t;
}

function bleFallback() {
  if (typeof BLE !== "undefined" && BLE.RPC && typeof BLE.RPC.call === "function") {
    print("shellyctl[" + CONFIG.linkId + "]: falling back to BLE RPC " + CONFIG.bleMac);
    BLE.RPC.call(CONFIG.bleMac, CONFIG.method, CONFIG.params, function (res, err_code, err_msg) {
      if (err_code === 0) {
        print("shellyctl[" + CONFIG.linkId + "]: BLE ok");
      } else {
        print("shellyctl[" + CONFIG.linkId + "]: BLE failed: " + err_msg);
      }
    });
  } else {
    print("shellyctl[" + CONFIG.linkId + "]: this firmware does not expose BLE RPC to scripts; cannot fall back");
  }
}

function onTrigger() {
  attempt++;
  let token = attempt;
  let done = false;
  let start = Date.now();
  let tmo = adaptiveTimeoutMs();
  print("shellyctl[" + CONFIG.linkId + "]: trigger " + CONFIG.srcComponent + "/" + CONFIG.srcEvent + ", LAN timeout " + tmo + "ms");
  // The HTTP timeout below only has 1s granularity, so this Timer races the
  // RPC callback for millisecond-granularity failover; first to fire wins.
  Timer.set(tmo, false, function () {
    if (done || token !== attempt) return;
    done = true;
    print("shellyctl[" + CONFIG.linkId + "]: LAN timed out after " + tmo + "ms");
    bleFallback();
  });
  Shelly.call("HTTP.POST", {
    url: "http://" + CONFIG.targetIp + "/rpc",
    body: JSON.stringify({ id: 1, src: "shellyctl-link", method: CONFIG.method, params: CONFIG.params }),
    timeout: CONFIG.httpTimeoutSec
  }, function (res, err_code, err_msg) {
    if (done || token !== attempt) return;
    done = true;
    let rtt = Date.now() - start;
    if (err_code === 0 && res && res.code === 200) {
      recordRtt(rtt);
      print("shellyctl[" + CONFIG.linkId + "]: LAN ok in " + rtt + "ms (ewma " + ((ewmaMs + 0.5) | 0) + "ms)");
    } else {
      print("shellyctl[" + CONFIG.linkId + "]: LAN failed after " + rtt + "ms: " + (err_msg ? err_msg : "HTTP " + (res ? JSON.stringify(res.code) : "?")));
      bleFallback();
    }
  });
}

Shelly.addEventHandler(function (event) {
  if (!event || !event.info) return;
  if (event.component === CONFIG.srcComponent && event.info.event === CONFIG.srcEvent) {
    onTrigger();
  }
});
