package scripts

import (
	"bytes"
	"fmt"
	"text/template"
)

// SurveyDurationMs is how long the deployed survey script scans BLE
// advertisements before it stops. Collect results only after this long.
const SurveyDurationMs = 12000

// SurveyScriptName is the script slot name used for the temporary
// BLE proximity survey.
const SurveyScriptName = "shellyctl-ble-survey"

var surveyTmpl = template.Must(template.New("survey").Parse(surveyTemplate))

// RenderSurvey produces the temporary mJS script that scans BLE
// advertisements and accumulates the strongest RSSI seen per neighbor
// address. The manager collects the accumulated map with
// Script.Eval("getResults()") and then removes the script.
func RenderSurvey() (string, error) {
	var buf bytes.Buffer
	if err := surveyTmpl.Execute(&buf, map[string]any{"DurationMs": SurveyDurationMs}); err != nil {
		return "", fmt.Errorf("scripts: render survey: %w", err)
	}
	return buf.String(), nil
}

const surveyTemplate = `// Generated by shellyctl -- temporary BLE proximity survey.
// Scans nearby BLE advertisements for {{.DurationMs}}ms and records the
// strongest RSSI per address. Removed automatically after collection.

let seen = {};

function getResults() {
  return JSON.stringify(seen);
}

if (typeof BLE === "undefined" || !BLE.Scanner || typeof BLE.Scanner.Subscribe !== "function") {
  seen["__error"] = { rssi: 0, count: 0, name: "this firmware does not expose the BLE scanner to scripts (is Bluetooth enabled?)" };
} else {
  BLE.Scanner.Subscribe(function (ev, res) {
    if (ev !== BLE.Scanner.SCAN_RESULT || !res || !res.addr) return;
    let e = seen[res.addr];
    if (!e) {
      e = { rssi: -999, count: 0, name: "" };
      seen[res.addr] = e;
    }
    if (res.rssi > e.rssi) e.rssi = res.rssi;
    e.count++;
    if (res.local_name && res.local_name.length > 0) e.name = res.local_name;
  });
  let h = BLE.Scanner.Start({ duration_ms: {{.DurationMs}}, active: true });
  if (h === null) {
    seen["__error"] = { rssi: 0, count: 0, name: "BLE scanner failed to start (radio busy or scan already running)" };
  } else {
    print("shellyctl-survey: scanning BLE for {{.DurationMs}}ms");
  }
}
`
